[features]
seeds = false
[programs.localnet]
token_lender = "32xQJkxLJNmWPtykFuBpdXrh7SxMpRwSkYUWY3Fa9cim"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/joesol/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# Token Metadata: Program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Pyth: Program
[[test.validator.clone]]
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"

# Pyth: SOL_USD
[[test.validator.clone]]
address = "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj"

# Pyth: USDC_USD
[[test.validator.clone]]
address = "8GWTTbNiXdmyZREXbjsZBmCRuzdPrW55dnZGDkTRjWvb"


[scripts]
test = "yarn run upload-json"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-lender.ts"
# pyth = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pyth.ts"